// src/components/AmountEdit.svelte
<script lang="typescript">
  import type BigNumber from "bignumber.js";
  import AutoNumeric from "autonumeric";
  import { onMount } from 'svelte';

  export let maxValue: BigNumber;

  let numericInput: HTMLInputElement;
  let numericValue = "0";
  let visible = maxValue.gt(0);

  onMount(() => {
    if (visible) {
      new AutoNumeric(numericInput, null, {
        decimalPlaces: 6,
        maximumValue: maxValue.toString(),
        selectOnFocus: false
      });
    }
  });

  const setMax = () => {
    //@ts-ignore
    AutoNumeric.set(numericInput, maxValue.toString());
  };

</script>

{#if visible}
  <input bind:this={numericInput} bind:value={numericValue} /> <a on:click={setMax} href="#">Max</a>
{/if}

// src/components/amount-edit.tsx
import { useRef, useEffect, useState } from "react";
import AutoNumeric from "autonumeric";

export default ({ maxValue, decimalPlaces }) => {
  const numericInput = useRef(null);
  const [isVisible, setVisible ] = useState(maxValue.gt(0));

  useEffect(() => {
    if (isVisible) {
      new AutoNumeric(numericInput.current, null, {
        decimalPlaces: decimalPlaces,
        maximumValue: maxValue.toString(),
        selectOnFocus: false
      });
    }
  }, []);

  const setMax = () => {
    //@ts-ignore
    AutoNumeric.set(numericInput.current, maxValue.toString());
  };

  if (isVisible) {
    return (
      <>
        <input ref={numericInput} defaultValue="0" /> <a onClick={setMax} href="#">Max</a>
      </>
    )
  }

  return null;
}
